name: Build and Deploy (docs)

on:
  push:
    paths:
      - "content/**"
      - "src/**"
      - "scripts/build.mjs"
      - "site.config.json"
      - ".github/workflows/build.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 의존성 없는 단일 빌드 스크립트이므로 npm install 단계 없음
      - name: Run build
        run: node scripts/build.mjs

      - name: Commit & Push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/ sitemap.xml robots.txt || true
          git commit -m "chore: build site" || echo "No changes to commit"
          git push
